import StyleDictionary from "style-dictionary";

StyleDictionary.registerTransform({
  name: "color/figma-hex",
  type: "value",
  filter: (token) => token.$type === "color",
  transform: (token) => {
    const value = token.$value ?? token.value;
    if (typeof value === "string") return value;
    if (value?.hex) return value.hex.toLowerCase();
    if (value?.components) {
      const [r, g, b] = value.components;
      const toHex = (n) =>
        Math.round(n * 255)
          .toString(16)
          .padStart(2, "0");
      return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
    }
    return value;
  },
});

StyleDictionary.registerTransform({
  name: "value/px",
  type: "value",
  filter: (token) => {
    const path = token.path.map((p) => p.toLowerCase());
    return path.some(
      (p) =>
        p.includes("radius") ||
        p.includes("stroke") ||
        p.includes("spacing") ||
        p.includes("size"),
    );
  },
  transform: (token) => {
    const value = token.$value ?? token.value;
    const num = parseFloat(value);
    if (isNaN(num) || num === 0) return "0";
    return `${num}px`;
  },
});

StyleDictionary.registerTransform({
  name: "name/figma-custom",
  type: "name",
  transform: (token) => {
    const type = token.$type;
    const path = token.path.map((p) => p.toLowerCase().replace(/\s+/g, "-"));
    const scale = path[path.length - 1];
    const isPrimitive = token.filePath?.includes("Global");

    if (isPrimitive) {
      if (type === "color") return `color-${path.join("-")}`;
      if (path.some((p) => p.includes("border-radius") || p.includes("radius")))
        return `radius-${scale}`;
      if (path.some((p) => p.includes("stroke"))) return `border-${scale}`;
      if (path.some((p) => p.includes("spacing") || p.includes("size")))
        return `spacing-${scale}`;
      return path.join("-");
    }

    if (type === "color") return `color-${path.join("-")}`;
    if (path.some((p) => p.includes("border-radius") || p.includes("radius")))
      return `radius-${path.join("-")}`;
    if (path.some((p) => p.includes("stroke")))
      return `border-width-${path.join("-")}`;
    if (path.some((p) => p.includes("spacing") || p.includes("size")))
      return `spacing-${path.join("-")}`;
    return path.join("-");
  },
});

StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .map((token) => {
        const value = token.$value ?? token.value;
        if (value === undefined || value === null) {
          console.warn(
            `Unresolved token: ${token.name}`,
            token.original.$value ?? token.original.value,
          );
          return `  /* UNRESOLVED: --${token.name} */`;
        }
        return `  --${token.name}: ${value};`;
      })
      .join("\n");

    return `/* Auto-generated by Style Dictionary. Do not edit directly. */\n\n@theme {\n${vars}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: "css/tailwind-theme-refs",
  format: ({ dictionary, options }) => {
    const selector = options?.selector;
    const indent = selector ? "    " : "  ";
    const aliasToPrimitiveVar = (targetName, tokenType) => {
      const parts = targetName
        .split("/")
        .map((p) => p.toLowerCase().replace(/\s+/g, "-"));
      const scale = parts[parts.length - 1];

      if (tokenType === "color") return `color-${parts.join("-")}`;
      if (
        parts.some((p) => p.includes("border-radius") || p.includes("radius"))
      )
        return `radius-${scale}`;
      if (parts.some((p) => p.includes("stroke"))) return `border-${scale}`;
      if (parts.some((p) => p.includes("spacing") || p.includes("size")))
        return `spacing-${scale}`;
      return parts.join("-");
    };

    const vars = dictionary.allTokens
      .map((token) => {
        const original = token.original.$value ?? token.original.value;

        if (
          typeof original === "string" &&
          original.startsWith("{") &&
          original.endsWith("}")
        ) {
          const refPath = original.slice(1, -1).split(".");

          const refToken = dictionary.allTokens.find(
            (t) =>
              t.path.length === refPath.length &&
              t.path.every(
                (p, i) => p.toLowerCase() === refPath[i].toLowerCase(),
              ),
          );

          if (refToken) {
            return `${indent}--${token.name}: var(--${refToken.name});`;
          }

          const path = refPath.map((p) => p.toLowerCase().replace(/\s+/g, "-"));
          const varName = `color-${path.join("-")}`;
          return `${indent}--${token.name}: var(--${varName});`;
        }

        const aliasData = token.original.$extensions?.["com.figma.aliasData"];
        if (
          aliasData?.targetVariableSetName === "Primitives" &&
          aliasData.targetVariableName
        ) {
          const primitiveVarName = aliasToPrimitiveVar(
            aliasData.targetVariableName,
            token.$type,
          );
          return `${indent}--${token.name}: var(--${primitiveVarName});`;
        }

        const value = token.$value ?? token.value;

        if (value === undefined || value === null) {
          console.warn(`⚠️  Unresolved token: ${token.name}`, original);
          return `${indent}/* UNRESOLVED: --${token.name} */`;
        }

        return `${indent}--${token.name}: ${value};`;
      })
      .join("\n");

    if (selector) {
      return `/* Auto-generated by Style Dictionary. Do not edit directly. */\n\n${selector} {\n${vars}\n}\n`;
    }
    return `/* Auto-generated by Style Dictionary. Do not edit directly. */\n\n@theme {\n${vars}\n}\n`;
  },
});

const transforms = ["name/figma-custom", "color/figma-hex", "value/px"];
const buildPath = "src/lib/styles/generated/";

async function build() {
  const globalSD = new StyleDictionary({
    source: ["src/lib/styles/**/Global.tokens.json"],
    usesDtcg: true,
    platforms: {
      css: {
        transforms,
        buildPath,
        files: [
          {
            destination: "primitives.css",
            format: "css/tailwind-theme",
          },
        ],
      },
    },
  });

  const lightSD = new StyleDictionary({
    source: [
      "src/lib/styles/**/Global.tokens.json",
      "src/lib/styles/**/Light.tokens.json",
    ],
    usesDtcg: true,
    platforms: {
      css: {
        transforms,
        buildPath,
        files: [
          {
            destination: "light.css",
            format: "css/tailwind-theme-refs",
            filter: (token) => token.filePath.includes("Light"),
          },
        ],
      },
    },
  });

  const darkSD = new StyleDictionary({
    source: [
      "src/lib/styles/**/Global.tokens.json",
      "src/lib/styles/**/Dark.tokens.json",
    ],
    usesDtcg: true,
    platforms: {
      css: {
        transforms,
        buildPath,
        files: [
          {
            destination: "dark.css",
            format: "css/tailwind-theme-refs",
            filter: (token) => token.filePath.includes("Dark"),
            options: { selector: ".dark" },
          },
        ],
      },
    },
  });

  await globalSD.buildAllPlatforms();
  await lightSD.buildAllPlatforms();
  await darkSD.buildAllPlatforms();

  console.log("\nTokens built successfully!");
}

build();
